# Don't edit this file
#
# It was auto generated by CMake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES naprender napscene napparameter napimgui napvideo)
set(DEEP_DEPENDENT_NAP_MODULES naprender napscene napparameter napimgui napvideo napfont napinput napcolor napmath napsdlinput napaudio napapp)
set(DEEP_DEPENDENT_RPATHS ../../../../system_modules/naprender/thirdparty/assimp/msvc/x86_64/lib ../../../../system_modules/naprender/thirdparty/assimp/msvc/x86_64/bin ../../../../system_modules/naprender/thirdparty/FreeImage/msvc/x86_64/Dist/x64 ../../../../system_modules/naprender/thirdparty/vulkansdk/msvc/x86_64/lib ../../../../system_modules/naprender/thirdparty/vulkansdk/msvc/x86_64/bin ../../../../system_modules/naprender/thirdparty/SDL2/msvc/x86_64/lib ../../../../system_modules/napvideo/thirdparty/ffmpeg/msvc/x86_64/bin ../../../../system_modules/napfont/thirdparty/freetype/msvc/x86_64/lib/Release ../../../../system_modules/napfont/thirdparty/freetype/msvc/x86_64/lib/Debug ../../../../system_modules/napaudio/thirdparty/mpg123/msvc/x86_64/lib ../../../../system_modules/napaudio/thirdparty/portaudio/msvc/x86_64/lib ../../../../system_modules/napaudio/thirdparty/libsndfile/msvc/x86_64/lib)
